### ISSUE TITLE
L06: Одна таблица на все итерации

### ISSUE THREAD

**Issue by matry-ny** [alexshvakel/newwork#3]
https://github.com/alexshvakel/newwork/blob/d2140d95496b539a4817d80e86f852fff9d70204/HomeWork/15.10.2020/homefunctions.php#L110

для цикла for нужно, чтобы для каждой итерации была одна и та же таблице с общим хедом. вывод не должен отличаться от цикла foreach

**Comment by alexshvakel** [comment]
все исправлено
